// Package ebuild implements ebuild execution engine.
//
// This file contains tests for archive extraction with timestamp preservation.
package ebuild

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// TestExtractTar_TimestampPreservation verifies that file timestamps
// from tar archives are preserved during extraction.
// This is critical for automake-based packages that use timestamps
// to determine if files like configure, Makefile.in need regeneration.
func TestExtractTar_TimestampPreservation(t *testing.T) {
	destDir := t.TempDir()

	// Create test archive with specific timestamps
	configureTime := time.Date(2022, 1, 31, 12, 0, 0, 0, time.UTC)
	configureAcTime := time.Date(2021, 6, 15, 10, 0, 0, 0, time.UTC)
	makefileInTime := time.Date(2022, 1, 30, 8, 0, 0, 0, time.UTC)

	files := []struct {
		name    string
		content string
		modTime time.Time
	}{
		{"test-1.0/configure", "#!/bin/sh\necho configure", configureTime},
		{"test-1.0/configure.ac", "AC_INIT([test], [1.0])", configureAcTime},
		{"test-1.0/Makefile.in", "all: ; echo build", makefileInTime},
	}

	// Create tar reader with test data
	tarReader := createTarReader(t, files)

	// Extract using helpers (nil env is ok for extractTar)
	var stdout, stderr bytes.Buffer
	helpers := NewHelpers(nil, &stdout, &stderr)

	if err := helpers.extractTar(tarReader, destDir); err != nil {
		t.Fatalf("extractTar failed: %v", err)
	}

	// Verify timestamps are preserved
	for _, f := range files {
		extractedPath := filepath.Join(destDir, f.name)
		info, err := os.Stat(extractedPath)
		if err != nil {
			t.Errorf("Failed to stat %s: %v", f.name, err)
			continue
		}

		// Allow 1 second tolerance for filesystem precision
		if diff := info.ModTime().Sub(f.modTime); diff < -time.Second || diff > time.Second {
			t.Errorf("Timestamp mismatch for %s:\n  expected: %v\n  got:      %v",
				f.name, f.modTime, info.ModTime())
		}
	}
}

// TestExtractTar_DirectoryTimestamps verifies that directory timestamps
// are also preserved during extraction.
func TestExtractTar_DirectoryTimestamps(t *testing.T) {
	destDir := t.TempDir()

	dirTime := time.Date(2021, 3, 15, 14, 30, 0, 0, time.UTC)
	fileTime := time.Date(2021, 3, 10, 9, 0, 0, 0, time.UTC)

	files := []struct {
		name    string
		content string
		modTime time.Time
		isDir   bool
	}{
		{"test-1.0/", "", dirTime, true},
		{"test-1.0/README", "Hello", fileTime, false},
	}

	tarReader := createTarReaderWithDirs(t, files)

	var stdout, stderr bytes.Buffer
	helpers := NewHelpers(nil, &stdout, &stderr)

	if err := helpers.extractTar(tarReader, destDir); err != nil {
		t.Fatalf("extractTar failed: %v", err)
	}

	// Check directory timestamp
	dirPath := filepath.Join(destDir, "test-1.0")
	dirInfo, err := os.Stat(dirPath)
	if err != nil {
		t.Fatalf("Failed to stat directory: %v", err)
	}

	if diff := dirInfo.ModTime().Sub(dirTime); diff < -time.Second || diff > time.Second {
		t.Errorf("Directory timestamp mismatch:\n  expected: %v\n  got:      %v",
			dirTime, dirInfo.ModTime())
	}
}

// TestExtractZip_TimestampPreservation verifies zip extraction preserves timestamps.
func TestExtractZip_TimestampPreservation(t *testing.T) {
	tmpDir := t.TempDir()
	destDir := filepath.Join(tmpDir, "dest")
	if err := os.MkdirAll(destDir, 0755); err != nil {
		t.Fatal(err)
	}

	archivePath := filepath.Join(tmpDir, "test.zip")
	fileTime := time.Date(2023, 5, 20, 16, 45, 0, 0, time.UTC)

	if err := createTestZip(archivePath, "test-1.0/main.go", "package main", fileTime); err != nil {
		t.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	helpers := NewHelpers(nil, &stdout, &stderr)

	if err := helpers.unpackZip(archivePath, destDir); err != nil {
		t.Fatalf("unpackZip failed: %v", err)
	}

	extractedPath := filepath.Join(destDir, "test-1.0/main.go")
	info, err := os.Stat(extractedPath)
	if err != nil {
		t.Fatalf("Failed to stat extracted file: %v", err)
	}

	// Zip has 2-second resolution
	if diff := info.ModTime().Sub(fileTime); diff < -2*time.Second || diff > 2*time.Second {
		t.Errorf("Timestamp mismatch:\n  expected: %v\n  got:      %v",
			fileTime, info.ModTime())
	}
}

// TestExtractTar_AutomakeScenario tests the specific scenario that was broken:
// extracting a GNU package where timestamps determine if autotools regeneration
// is needed.
func TestExtractTar_AutomakeScenario(t *testing.T) {
	destDir := t.TempDir()

	// Simulate real GNU hello package timestamps
	// Key: aclocal.m4 MUST be newer than m4/*.m4 files
	aclocalTime := time.Date(2022, 1, 31, 21, 46, 27, 0, time.UTC) // Newest
	m4FileTime := time.Date(2021, 3, 8, 0, 43, 25, 0, time.UTC)    // Older

	files := []struct {
		name    string
		content string
		modTime time.Time
	}{
		{"hello-2.12/aclocal.m4", "# generated by aclocal", aclocalTime},
		{"hello-2.12/m4/00gnulib.m4", "dnl gnulib m4", m4FileTime},
	}

	tarReader := createTarReader(t, files)

	var stdout, stderr bytes.Buffer
	helpers := NewHelpers(nil, &stdout, &stderr)

	if err := helpers.extractTar(tarReader, destDir); err != nil {
		t.Fatalf("extractTar failed: %v", err)
	}

	// Verify the critical invariant: aclocal.m4 must be newer than m4/*.m4
	aclocalPath := filepath.Join(destDir, "hello-2.12/aclocal.m4")
	m4FilePath := filepath.Join(destDir, "hello-2.12/m4/00gnulib.m4")

	aclocalInfo, err := os.Stat(aclocalPath)
	if err != nil {
		t.Fatalf("Failed to stat aclocal.m4: %v", err)
	}

	m4FileInfo, err := os.Stat(m4FilePath)
	if err != nil {
		t.Fatalf("Failed to stat m4/00gnulib.m4: %v", err)
	}

	if !aclocalInfo.ModTime().After(m4FileInfo.ModTime()) {
		t.Errorf("CRITICAL: aclocal.m4 must be newer than m4/*.m4 files!\n"+
			"  aclocal.m4:      %v\n"+
			"  m4/00gnulib.m4:  %v\n"+
			"This would cause make to regenerate autotools files!",
			aclocalInfo.ModTime(), m4FileInfo.ModTime())
	}
}

// Helper functions for creating test archives

func createTarReader(t *testing.T, files []struct {
	name    string
	content string
	modTime time.Time
}) *tar.Reader {
	t.Helper()

	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)

	// Track directories to add
	dirs := make(map[string]time.Time)

	for _, file := range files {
		dir := filepath.Dir(file.name)
		if dir != "." && dir != "" {
			// Add immediate parent
			if _, exists := dirs[dir]; !exists {
				dirs[dir] = file.modTime
			}
			// Add root directory if multi-level
			parts := splitPath(dir)
			if len(parts) > 1 {
				if _, exists := dirs[parts[0]]; !exists {
					dirs[parts[0]] = file.modTime
				}
			}
		}
	}

	// Add directories first
	for dir, modTime := range dirs {
		header := &tar.Header{
			Name:     dir + "/",
			Mode:     0755,
			Typeflag: tar.TypeDir,
			ModTime:  modTime,
		}
		if err := tw.WriteHeader(header); err != nil {
			t.Fatal(err)
		}
	}

	// Add files
	for _, file := range files {
		header := &tar.Header{
			Name:     file.name,
			Size:     int64(len(file.content)),
			Mode:     0644,
			Typeflag: tar.TypeReg,
			ModTime:  file.modTime,
		}
		if err := tw.WriteHeader(header); err != nil {
			t.Fatal(err)
		}
		if _, err := tw.Write([]byte(file.content)); err != nil {
			t.Fatal(err)
		}
	}

	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}

	return tar.NewReader(&buf)
}

func createTarReaderWithDirs(t *testing.T, files []struct {
	name    string
	content string
	modTime time.Time
	isDir   bool
}) *tar.Reader {
	t.Helper()

	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)

	for _, file := range files {
		if file.isDir {
			header := &tar.Header{
				Name:     file.name,
				Mode:     0755,
				Typeflag: tar.TypeDir,
				ModTime:  file.modTime,
			}
			if err := tw.WriteHeader(header); err != nil {
				t.Fatal(err)
			}
		} else {
			header := &tar.Header{
				Name:     file.name,
				Size:     int64(len(file.content)),
				Mode:     0644,
				Typeflag: tar.TypeReg,
				ModTime:  file.modTime,
			}
			if err := tw.WriteHeader(header); err != nil {
				t.Fatal(err)
			}
			if _, err := tw.Write([]byte(file.content)); err != nil {
				t.Fatal(err)
			}
		}
	}

	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}

	return tar.NewReader(&buf)
}

func splitPath(path string) []string {
	var parts []string
	for path != "" && path != "." {
		dir, file := filepath.Split(path)
		if file != "" {
			parts = append([]string{file}, parts...)
		}
		path = filepath.Clean(dir)
		if path == "." {
			break
		}
	}
	return parts
}

func createTestZip(path, fileName, content string, modTime time.Time) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	zw := zip.NewWriter(f)
	defer func() { _ = zw.Close() }()

	// Create directory entry
	dir := filepath.Dir(fileName)
	if dir != "." && dir != "" {
		header := &zip.FileHeader{
			Name:     filepath.ToSlash(dir) + "/",
			Method:   zip.Store,
			Modified: modTime,
		}
		header.SetMode(0755 | os.ModeDir)
		if _, err := zw.CreateHeader(header); err != nil {
			return err
		}
	}

	// Create file entry
	header := &zip.FileHeader{
		Name:     filepath.ToSlash(fileName),
		Method:   zip.Deflate,
		Modified: modTime,
	}
	header.SetMode(0644)

	w, err := zw.CreateHeader(header)
	if err != nil {
		return err
	}

	if _, err := w.Write([]byte(content)); err != nil {
		return err
	}

	return nil
}

// BenchmarkExtractTar benchmarks tar extraction with timestamp preservation.
func BenchmarkExtractTar(b *testing.B) {
	// Create test data once
	files := make([]struct {
		name    string
		content string
		modTime time.Time
	}, 50)

	for i := 0; i < 50; i++ {
		files[i] = struct {
			name    string
			content string
			modTime time.Time
		}{
			name:    "bench-1.0/file" + string(rune('a'+i%26)) + ".txt",
			content: string(bytes.Repeat([]byte("x"), 100)),
			modTime: time.Now().Add(-time.Duration(i) * time.Hour),
		}
	}

	// Create tar data
	var tarBuf bytes.Buffer
	tw := tar.NewWriter(&tarBuf)

	// Add root directory
	_ = tw.WriteHeader(&tar.Header{
		Name:     "bench-1.0/",
		Mode:     0755,
		Typeflag: tar.TypeDir,
		ModTime:  time.Now(),
	})

	for _, file := range files {
		header := &tar.Header{
			Name:     file.name,
			Size:     int64(len(file.content)),
			Mode:     0644,
			Typeflag: tar.TypeReg,
			ModTime:  file.modTime,
		}
		_ = tw.WriteHeader(header)
		_, _ = tw.Write([]byte(file.content))
	}
	_ = tw.Close()

	tarData := tarBuf.Bytes()

	var stdout, stderr bytes.Buffer
	helpers := NewHelpers(nil, &stdout, &stderr)

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		destDir := b.TempDir()
		tarReader := tar.NewReader(bytes.NewReader(tarData))

		if err := helpers.extractTar(tarReader, destDir); err != nil {
			b.Fatal(err)
		}
	}
}
