// Package cli provides command-line interface components for GRPM.
package cli

import (
	"fmt"
	"sort"
	"strings"
)

// CompletionGenerator generates shell completion scripts for GRPM.
//
// It uses CommandMeta from the CommandRegistry to generate static completion
// scripts for bash, zsh, and fish shells. This provides completion for:
//   - Command names (e.g., emerge, resolve, install)
//   - Flag names (e.g., --pretend, -p, --repo)
//
// Dynamic completion (package names from repository) is out of scope for Phase 1.
type CompletionGenerator struct {
	registry *CommandRegistry
}

// NewCompletionGenerator creates a new CompletionGenerator with all GRPM commands.
func NewCompletionGenerator() *CompletionGenerator {
	return &CompletionGenerator{
		registry: NewCommandRegistry(),
	}
}

// GenerateBash generates a bash completion script for GRPM.
//
// The generated script provides completion for:
//   - Commands (emerge, resolve, install, etc.)
//   - Flags for each command (--pretend, --repo, etc.)
//
// Installation:
//
//	grpm completion bash > /etc/bash_completion.d/grpm
//	# Or for user-local installation:
//	grpm completion bash >> ~/.bashrc
func (g *CompletionGenerator) GenerateBash() string {
	var sb strings.Builder

	// Header with installation instructions
	sb.WriteString("# GRPM bash completion script\n")
	sb.WriteString("# Generated by: grpm completion bash\n")
	sb.WriteString("#\n")
	sb.WriteString("# Installation:\n")
	sb.WriteString("#   grpm completion bash > /etc/bash_completion.d/grpm\n")
	sb.WriteString("#   # Or for user-local installation:\n")
	sb.WriteString("#   grpm completion bash >> ~/.bashrc\n")
	sb.WriteString("#   source ~/.bashrc\n")
	sb.WriteString("\n")

	// Main completion function
	sb.WriteString("_grpm() {\n")
	sb.WriteString("    local cur prev words cword\n")
	sb.WriteString("    _init_completion || return\n")
	sb.WriteString("\n")

	// Get all command names
	commands := g.registry.All()
	cmdNames := make([]string, 0, len(commands))
	for _, cmd := range commands {
		cmdNames = append(cmdNames, cmd.Name)
		// Add aliases
		cmdNames = append(cmdNames, cmd.Aliases...)
	}
	sort.Strings(cmdNames)

	// Command completion
	sb.WriteString("    # Commands\n")
	sb.WriteString(fmt.Sprintf("    local commands=\"%s\"\n", strings.Join(cmdNames, " ")))
	sb.WriteString("\n")

	// Global flags
	sb.WriteString("    # Global flags\n")
	sb.WriteString("    local global_flags=\"--help -h --version -V -v -vv -vvv\"\n")
	sb.WriteString("\n")

	// Command-specific flags
	sb.WriteString("    # Command-specific flags\n")
	for _, cmd := range commands {
		flags := g.collectBashFlags(cmd.Flags)
		if len(flags) > 0 {
			sb.WriteString(fmt.Sprintf("    local %s_flags=\"%s\"\n", bashSafeName(cmd.Name), strings.Join(flags, " ")))
		}
	}
	sb.WriteString("\n")

	// Completion logic
	sb.WriteString("    # Determine which command is being used\n")
	sb.WriteString("    local cmd=\"\"\n")
	sb.WriteString("    for ((i=1; i < cword; i++)); do\n")
	sb.WriteString("        case \"${words[i]}\" in\n")
	for _, cmd := range commands {
		names := append([]string{cmd.Name}, cmd.Aliases...)
		sb.WriteString(fmt.Sprintf("            %s)\n", strings.Join(names, "|")))
		sb.WriteString(fmt.Sprintf("                cmd=\"%s\"\n", cmd.Name))
		sb.WriteString("                break\n")
		sb.WriteString("                ;;\n")
	}
	sb.WriteString("        esac\n")
	sb.WriteString("    done\n")
	sb.WriteString("\n")

	// Complete based on context
	sb.WriteString("    # Complete based on context\n")
	sb.WriteString("    if [[ -z \"$cmd\" ]]; then\n")
	sb.WriteString("        # No command yet - complete commands and global flags\n")
	sb.WriteString("        if [[ \"$cur\" == -* ]]; then\n")
	sb.WriteString("            COMPREPLY=($(compgen -W \"$global_flags\" -- \"$cur\"))\n")
	sb.WriteString("        else\n")
	sb.WriteString("            COMPREPLY=($(compgen -W \"$commands\" -- \"$cur\"))\n")
	sb.WriteString("        fi\n")
	sb.WriteString("        return\n")
	sb.WriteString("    fi\n")
	sb.WriteString("\n")

	// Command-specific completion
	sb.WriteString("    # Command-specific flag completion\n")
	sb.WriteString("    if [[ \"$cur\" == -* ]]; then\n")
	sb.WriteString("        case \"$cmd\" in\n")
	for _, cmd := range commands {
		flags := g.collectBashFlags(cmd.Flags)
		if len(flags) > 0 {
			sb.WriteString(fmt.Sprintf("            %s)\n", cmd.Name))
			sb.WriteString(fmt.Sprintf("                COMPREPLY=($(compgen -W \"$%s_flags\" -- \"$cur\"))\n", bashSafeName(cmd.Name)))
			sb.WriteString("                ;;\n")
		}
	}
	sb.WriteString("            *)\n")
	sb.WriteString("                COMPREPLY=($(compgen -W \"$global_flags\" -- \"$cur\"))\n")
	sb.WriteString("                ;;\n")
	sb.WriteString("        esac\n")
	sb.WriteString("        return\n")
	sb.WriteString("    fi\n")
	sb.WriteString("\n")

	// Default to file completion for non-flag arguments
	sb.WriteString("    # Default to file completion for package/path arguments\n")
	sb.WriteString("    _filedir\n")
	sb.WriteString("}\n")
	sb.WriteString("\n")

	// Register completion
	sb.WriteString("complete -F _grpm grpm\n")

	return sb.String()
}

// GenerateZsh generates a zsh completion script for GRPM.
//
// Installation:
//
//	grpm completion zsh > ~/.zsh/completions/_grpm
//	# Then ensure ~/.zsh/completions is in your fpath
func (g *CompletionGenerator) GenerateZsh() string {
	var sb strings.Builder

	// Header
	sb.WriteString("#compdef grpm\n")
	sb.WriteString("\n")
	sb.WriteString("# GRPM zsh completion script\n")
	sb.WriteString("# Generated by: grpm completion zsh\n")
	sb.WriteString("#\n")
	sb.WriteString("# Installation:\n")
	sb.WriteString("#   grpm completion zsh > ~/.zsh/completions/_grpm\n")
	sb.WriteString("#   # Ensure ~/.zsh/completions is in fpath:\n")
	sb.WriteString("#   # fpath=(~/.zsh/completions $fpath)\n")
	sb.WriteString("#   # autoload -Uz compinit && compinit\n")
	sb.WriteString("\n")

	// Helper function for flag descriptions
	sb.WriteString("_grpm() {\n")
	sb.WriteString("    local curcontext=\"$curcontext\" state line\n")
	sb.WriteString("    typeset -A opt_args\n")
	sb.WriteString("\n")

	// Main arguments specification
	sb.WriteString("    _arguments -C \\\n")
	sb.WriteString("        '(-h --help)'{-h,--help}'[Show help information]' \\\n")
	sb.WriteString("        '(-V --version)'{-V,--version}'[Show version information]' \\\n")
	sb.WriteString("        '-v[Verbose output level 1]' \\\n")
	sb.WriteString("        '-vv[Verbose output level 2]' \\\n")
	sb.WriteString("        '-vvv[Verbose output level 3]' \\\n")
	sb.WriteString("        '1: :_grpm_commands' \\\n")
	sb.WriteString("        '*::arg:->args'\n")
	sb.WriteString("\n")

	// Handle subcommand completion
	sb.WriteString("    case $state in\n")
	sb.WriteString("        args)\n")
	sb.WriteString("            case $words[1] in\n")

	// Generate completion for each command
	commands := g.registry.All()
	for _, cmd := range commands {
		names := append([]string{cmd.Name}, cmd.Aliases...)
		sb.WriteString(fmt.Sprintf("                %s)\n", strings.Join(names, "|")))
		sb.WriteString(fmt.Sprintf("                    _grpm_%s\n", zshSafeName(cmd.Name)))
		sb.WriteString("                    ;;\n")
	}

	sb.WriteString("            esac\n")
	sb.WriteString("            ;;\n")
	sb.WriteString("    esac\n")
	sb.WriteString("}\n")
	sb.WriteString("\n")

	// Command list function
	sb.WriteString("_grpm_commands() {\n")
	sb.WriteString("    local commands\n")
	sb.WriteString("    commands=(\n")
	for _, cmd := range commands {
		// Escape single quotes in description
		desc := strings.ReplaceAll(cmd.Short, "'", "'\\''")
		sb.WriteString(fmt.Sprintf("        '%s:%s'\n", cmd.Name, desc))
	}
	sb.WriteString("    )\n")
	sb.WriteString("    _describe -t commands 'grpm command' commands\n")
	sb.WriteString("}\n")
	sb.WriteString("\n")

	// Generate function for each command
	for _, cmd := range commands {
		sb.WriteString(g.generateZshCommandFunction(cmd))
		sb.WriteString("\n")
	}

	// Call the main function
	sb.WriteString("_grpm \"$@\"\n")

	return sb.String()
}

// GenerateFish generates a fish completion script for GRPM.
//
// Installation:
//
//	grpm completion fish > ~/.config/fish/completions/grpm.fish
func (g *CompletionGenerator) GenerateFish() string {
	var sb strings.Builder

	// Header
	sb.WriteString("# GRPM fish completion script\n")
	sb.WriteString("# Generated by: grpm completion fish\n")
	sb.WriteString("#\n")
	sb.WriteString("# Installation:\n")
	sb.WriteString("#   grpm completion fish > ~/.config/fish/completions/grpm.fish\n")
	sb.WriteString("\n")

	// Disable file completion by default
	sb.WriteString("# Disable file completion for grpm\n")
	sb.WriteString("complete -c grpm -f\n")
	sb.WriteString("\n")

	// Global flags
	sb.WriteString("# Global flags\n")
	sb.WriteString("complete -c grpm -n '__fish_use_subcommand' -s h -l help -d 'Show help information'\n")
	sb.WriteString("complete -c grpm -n '__fish_use_subcommand' -s V -l version -d 'Show version information'\n")
	sb.WriteString("complete -c grpm -n '__fish_use_subcommand' -s v -d 'Verbose output level 1'\n")
	sb.WriteString("\n")

	// Commands
	sb.WriteString("# Commands\n")
	commands := g.registry.All()
	for _, cmd := range commands {
		// Escape single quotes in description
		desc := strings.ReplaceAll(cmd.Short, "'", "\\'")
		sb.WriteString(fmt.Sprintf("complete -c grpm -n '__fish_use_subcommand' -a '%s' -d '%s'\n", cmd.Name, desc))

		// Add aliases
		for _, alias := range cmd.Aliases {
			sb.WriteString(fmt.Sprintf("complete -c grpm -n '__fish_use_subcommand' -a '%s' -d 'Alias for %s'\n", alias, cmd.Name))
		}
	}
	sb.WriteString("\n")

	// Command-specific flags
	sb.WriteString("# Command-specific flags\n")
	for _, cmd := range commands {
		if len(cmd.Flags) == 0 {
			continue
		}

		// Create condition that includes command and all aliases
		names := append([]string{cmd.Name}, cmd.Aliases...)
		conditions := make([]string, len(names))
		for i, name := range names {
			conditions[i] = fmt.Sprintf("__fish_seen_subcommand_from %s", name)
		}
		condition := strings.Join(conditions, "; or ")

		sb.WriteString(fmt.Sprintf("# %s flags\n", cmd.Name))
		for _, f := range cmd.Flags {
			if f.Hidden {
				continue
			}

			// Escape single quotes in description
			desc := strings.ReplaceAll(f.Description, "'", "\\'")

			// Build the complete command
			var parts []string
			parts = append(parts, fmt.Sprintf("complete -c grpm -n '%s'", condition))

			if f.Short != "" {
				parts = append(parts, fmt.Sprintf("-s %s", f.Short))
			}
			parts = append(parts, fmt.Sprintf("-l %s", f.Long))

			// Add argument requirement for non-bool flags
			if f.Type != "bool" && f.Type != "" {
				parts = append(parts, "-r") // requires argument
			}

			parts = append(parts, fmt.Sprintf("-d '%s'", desc))

			sb.WriteString(strings.Join(parts, " ") + "\n")
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

// GetInstallInstructions returns installation instructions for all shells.
func GetInstallInstructions() string {
	return `Shell Completion Installation Instructions

Bash:
  grpm completion bash > /etc/bash_completion.d/grpm
  # Or for user-local installation:
  grpm completion bash >> ~/.bashrc
  source ~/.bashrc

Zsh:
  mkdir -p ~/.zsh/completions
  grpm completion zsh > ~/.zsh/completions/_grpm
  # Add to ~/.zshrc:
  fpath=(~/.zsh/completions $fpath)
  autoload -Uz compinit && compinit

Fish:
  grpm completion fish > ~/.config/fish/completions/grpm.fish
`
}

// collectBashFlags extracts flag names for bash completion.
func (g *CompletionGenerator) collectBashFlags(flags []FlagMeta) []string {
	var result []string
	for _, f := range flags {
		if f.Hidden {
			continue
		}
		if f.Short != "" {
			result = append(result, "-"+f.Short)
		}
		result = append(result, "--"+f.Long)
	}
	return result
}

// generateZshCommandFunction generates a zsh completion function for a command.
func (g *CompletionGenerator) generateZshCommandFunction(cmd CommandMeta) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("_grpm_%s() {\n", zshSafeName(cmd.Name)))
	sb.WriteString("    _arguments -s \\\n")

	for i, f := range cmd.Flags {
		if f.Hidden {
			continue
		}

		// Escape single quotes in description
		desc := strings.ReplaceAll(f.Description, "'", "'\\''")

		// Build flag specification
		var spec string
		if f.Short != "" && f.Long != "" {
			// Both short and long form
			spec = fmt.Sprintf("'(-%s --%s)'{-%s,--%s}'", f.Short, f.Long, f.Short, f.Long)
		} else if f.Long != "" {
			// Long form only
			spec = fmt.Sprintf("'--%s'", f.Long)
		}

		// Add argument placeholder for non-bool flags
		if f.Type != "bool" && f.Type != "" {
			spec += fmt.Sprintf("[%s]:%s type:_files", desc, f.Type)
		} else {
			spec += fmt.Sprintf("[%s]", desc)
		}

		// Add line continuation for all but last
		if i < len(cmd.Flags)-1 {
			sb.WriteString(fmt.Sprintf("        %s \\\n", spec))
		} else {
			sb.WriteString(fmt.Sprintf("        %s \\\n", spec))
		}
	}

	// Allow file arguments for package/path specifications
	sb.WriteString("        '*:package:_files'\n")
	sb.WriteString("}\n")

	return sb.String()
}

// bashSafeName converts a command name to a safe bash variable name.
func bashSafeName(name string) string {
	return strings.ReplaceAll(name, "-", "_")
}

// zshSafeName converts a command name to a safe zsh function name.
func zshSafeName(name string) string {
	return strings.ReplaceAll(name, "-", "_")
}
